global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'ingest'
    static_configs:
      - targets: ['host.docker.internal:8000', 'localhost:8000']
  - job_name: 'producer' 
    static_configs:
      - targets: ['host.docker.internal:8002', 'localhost:8002']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
